#!/bin/bash

set -e  # Exit immediately if a command fails

echo "🧹 Cleaning..."
make clean

echo "📦 Building dist_macos... (change locally to dist_macos or dist_linux depending system)"
make dist_macos

echo "📦 Building dist_dmcp..."
make dist_dmcp

echo "📦 Building dist_dmcp5..."
make dist_dmcp5

echo "📦 Building dist_dmcp5r47..."
make dist_dmcp5r47

echo "📦 Building dist_dmcpr47..."
make dist_dmcpr47

echo "📦 Building dist_dmcp...package 1"
make DMCP_PACKAGE=1 dist_dmcp

echo "📦 Building dist_dmcp...package 2"
make DMCP_PACKAGE=2 dist_dmcp

echo "📦 Building dist_dmcp...package 3"
make DMCP_PACKAGE=3 dist_dmcp

echo "✅ All builds complete."

