#!/usr/bin/env python3
"""Thin entry-point for package management commands.

Usage:
    ./package refresh PACKAGE
    ./package materialize PACKAGE REL
    ./package rebase PACKAGE --onto REF
    ./package build PACKAGE
    ./package audit PACKAGE
    ./package status PACKAGE [--onto REF]
    ./package integrate PACKAGE --onto REF [--keep] [--no-build]
    ./package resume SESSION [--keep] [--no-build]
    ./package upstream PACKAGES [--onto REF] [--branch BRANCH] [--remote REMOTE] [--push] [--mr] [--no-build] [--keep]
"""
import os
import sys

sys.path.insert(0,
                os.path.join(os.path.dirname(os.path.abspath(__file__)),
                             'tools'))

from pkg_patch_cli import main  # noqa: E402


if __name__ == '__main__':
    sys.exit(main())
