#!/bin/bash

forcecrc32=$1
input=$2
output=$3

if [[ "$OSTYPE" == "darwin"* ]]; then
        # Host is Mac: use gstat for GNU version
        STAT=gstat
else
        # Assume host is Linux: stat is GNU version
        STAT=stat
fi



filesize() {
  $STAT -Lc%s "$1"
}


if [ ! -f "$input" ];then
  echo "ERROR: Missing qspi file '$input'"
  exit 1
fi

sz=`filesize $input`

dir=`dirname $input`

cp $input $output
echo -n -e '\x00\x00\x00\x00' >> $output
$forcecrc32 $output $sz 000CFED6

